# Hexo 配置
## 文档：https://hexo.io/docs/configuration.html
## 来源：https://github.com/hexojs/hexo/

# 站点基本信息
title: "清明"                      # 站点标题，显示在浏览器标签和网站头部
subtitle: '十行俱下犹觉浅，一朝闭门书五车'  # 站点副标题，显示在标题下方
description: ''                      # 站点描述，用于 SEO 和搜索引擎展示
keywords: ''                         # 站点关键词，SEO 优化用
author: "清明"                      # 作者名称
language: zh-CN                      # 站点语言，影响主题显示和 SEO
timezone: Asia/Shanghai               # 站点时区，影响文章发布时间显示

# URL
## 在这里设置你的网站网址
url: https://qm-blog.vercel.app
permalink: :year/:month/:day/:title/  # 文章永久链接格式
permalink_defaults: {}                # 永久链接默认值
pretty_urls:                          # 美化 URL
  trailing_index: true                # 去除 index.html
  trailing_html: true                 # 去除 .html

# 目录结构
source_dir: source                    # 源文件目录
public_dir: public                    # 生成的静态文件目录
tag_dir: tags                         # 标签目录
archive_dir: archives                 # 归档目录
category_dir: categories              # 分类目录
code_dir: downloads/code              # 代码目录
i18n_dir: :lang                       # 多语言目录
skip_render:                          # 跳过渲染的文件或目录
  - "*.pdf"
  - "assets/**"
  - "downloads/**"
  - "images/**"

# 写作设置
new_post_name: :title.md              # 新帖子的文件名
default_layout: post                  # 默认布局
titlecase: false                      # 将 title 转换为 titlecase
external_link:                        # 外部链接设置
  enable: true                        # 在新选项卡中打开外部链接
  field: site                         # 适用于整个站点
  exclude: ''                         # 排除的链接
  open_in_new_tab: true               # 在新标签页中打开
filename_case: 0                      # 文件名大小写（0=不变，1=小写，2=大写）
render_drafts: false                  # 是否渲染草稿
post_asset_folder: true               # 是否为每篇文章创建一个资源文件夹
relative_link: false                  # 是否使用相对链接
future: true                          # 是否发布未来的文章
syntax_highlighter: highlight.js      # 语法高亮引擎
highlight:                             # highlight.js 设置
  line_number: true                   # 显示行号
  auto_detect: true                   # 自动检测语言
  tab_replace: ''                     # 替换制表符
  wrap: true                          # 包裹代码块
  hljs: true                          # 使用内置的 highlight.js 样式
prismjs:                               # Prism.js 设置
  preprocess: true                    # 预处理代码块
  line_number: true                   # 显示行号
  tab_replace: ''                     # 替换制表符

# 主页设置
index_generator:
  path: ''                            # 博客索引页的根路径
  per_page: 7                         # 每页文章数
  order_by: -date                     # 按日期降序排序

# 分类标签
default_category: "未分类"            # 默认分类
category_map: {}                      # 分类映射
tag_map: {}                           # 标签映射

# 元数据
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# 日期/时间格式
## Hexo 使用 Moment.js 解析和显示日期
## 可以自定义日期格式
## http://momentjs.com/docs/#/displaying/format/
date_format: "YYYY年MM月DD日"         # 文章日期格式
time_format: "HH:mm:ss"              # 文章时间格式
## updated_option supports 'mtime', 'date', 'empty' options
updated_option: 'date'                # 文章更新时间选项

# 分页
## 设置 per_page 为 0 禁用分页
per_page: 7
pagination_dir: page

# 包含/排除文件
## include:/exclude: options 只适用于 `source/` 文件夹
include: []
exclude: []
ignore: []

# 扩展
## 插件：https://hexo.io/plugins/
## 主题：https://hexo.io/themes/
theme: tranquility

# 部署
## 文档：https://hexo.io/docs/one-command-deployment
deploy:
  type: vercel
